services:
  qubic-events-publisher:
    image: ghcr.io/qubic/go-events-publisher:latest # set correct version
    container_name: qubic-events-publisher
    ports:
      - "127.0.0.1:9999:9999"
    environment:
      QUBIC_EVENTS_PUBLISHER_CLIENT_EVENT_API_URL: "qubic-events:8001" # set qubic event service grpc url here
      QUBIC_EVENTS_PUBLISHER_BROKER_BOOTSTRAP_SERVERS: "kafka:9092" # set kafka url here
      QUBIC_EVENTS_PUBLISHER_SYNC_START_EPOCH: 155 # set epoch to start with
      QUBIC_EVENTS_PUBLISHER_SYNC_ENABLED: false # comment or set to true
    volumes:
      - ./store/qubic-events-publisher:/app/store
    networks:
      - qubic
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://127.0.0.1:9999/status" ]
      interval: 15s
      timeout: 3s
      retries: 3
networks:
  qubic:
